In [2]:
print("hello world")

hello world


In [3]:
print("shifa")

shifa


In [4]:
shifa=2
print(shifa)

2


In [5]:
type(shifa)

int

In [6]:
id(2+5)

2828936374768

In [7]:
id(1+5)

2828936374736

In [8]:
a=2
b=3
c=0
print(id(c))
c=a+b
print(id(c))
print(id(b))

2828936374544
2828936374704
2828936374640


In [9]:
id(b)

2828936374640

In [10]:
help()


Welcome to Python 3.9's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.9/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
# Varibles can store different type of data 

In [12]:
#Tuples
#strings
# dictionaries
#lists


In [13]:
a="My 2 code"

In [14]:
type(a)

str

In [15]:
a=2
type(a)

int

In [16]:
a=[1,2,3,4]
type(a)

list

In [17]:
a={c:1,b:2}
type(a)

dict

In [18]:
# We are going to make a calculator that takes the input from the user and calculates the sum

In [19]:
# When we require input from the user we use the input command
#input("enter a")
# Now here the string in the brackets "enter a" will pop up on screen while taking input
#a=input("enter a")
#you can store it in a variable for further use

In [20]:
c=input("Hello give me a value")

Hello give me a value2


In [21]:
c

'2'

In [22]:
b=input("Hello give me a value")

Hello give me a value2


In [23]:
int(c)+int(b)

4

In [24]:
id(5)




2828936374704

In [25]:
id(6)

2828936374736

In [26]:
id(5+6)

2828936374896

In [27]:
a=6
b=5
print(id(a))
print(id(b))
c=a+b
print(id(c))

2828936374736
2828936374704
2828936374896


In [28]:
print(c)


11


In [29]:
a='laiba'

In [30]:
print("My Name is",a)

My Name is laiba


In [31]:
b='16 years old'

In [32]:
print("iam",b)

iam 16 years old


In [33]:
s="My name is zohair"
s1="i am 21 years old"
s2="i am a chemical engineer"
print(s,s1,s2)

My name is zohair i am 21 years old i am a chemical engineer


In [34]:
n='uku7k'
m='hdjdjd'
k='hhhsh'
print(n,m,k)

uku7k hdjdjd hhhsh


In [35]:
m='3'
l='4'
e='9'
r='6'
print(m,l,e,r)

3 4 9 6


In [36]:
s='kll'
print(s)

kll


In [37]:
g=99
m=88
print(id(g))
print(id(m))

2828936566192
2828936565840


In [38]:
k="laiba"

In [39]:
m="khalid"

In [40]:
print(k,m)

laiba khalid


In [41]:
1)Floating:A data type representing numbers with fractional.for example:-8.76,0.0,3.145
2)Boolean:A data type representing logical true or false.for example:true,false
3)Integer:A data type representing whole numbers.for example:-5,0,123 
4)String:A data type representing a sequence of characters.for example:"hello world!"
5)nothing:no data.for example:null
        
        
        
 . your name____A string of charchter.

.your age_____usually an integer. 
.the amount of money in your pocket – usually a value measured in dollars and cents (something with a fractional part).


SyntaxError: unmatched ')' (2765912919.py, line 1)

In [42]:
# is thew data being stored in the variable

In [43]:
a=10
b=10
print(id(a))
print(id(b))


2828936374864
2828936374864


In [44]:
3/2

1.5

In [45]:
a=1.5
type(a)


float

In [46]:
x=2
a=2+2*x
type(a)
print(a)

6


In [47]:
complex(3,2)

(3+2j)

In [48]:
a=2
b=3
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

False
True
False
True
False
True


In [49]:
print(bool(0))
print(bool(1))
print(bool(2))
print(bool(10))

False
True
True
True


In [51]:
cls

In [52]:
f=2
i=2.5
s=23
print(f,s,i)

2 23 2.5


In [53]:
float(2)

2.0

In [57]:
int(2.5)


2

In [55]:
str(23)

'23'

In [63]:
a=input("enter the value of a")
b=input("enter the value of b")
e=int(a)
f=int(b)
c=2*e*3
d=f/3
print (c>d)

enter the value of a2
enter the value of b3
True


In [3]:
a=input("enter the value of a")
b=input("enter the value of b")
s=int(a)
g=int(b)
c=2*s*3
d=g/2
print (c>d)

enter the value of a3
enter the value of b2
True


In [2]:
a=input("enter the value of a")
b=input("enter the value of b")
s=int(a)
g=int(b)
c=2*s*3
d=g/2
print(c>d)


enter the value of a3
enter the value of b2
True


In [12]:
j=input("enter the value of j")
h=input("enter the value of h")
l=int(j)
s=int(h)
f=3*j*7
k=s/9
print(f<k)


enter the value of j3
enter the value of h9
False


In [3]:
m=input("enter the value of m")
o=input("enter the value of o")
b=int(m)
n=int(o)
b>n

enter the value of m8
enter the value of o0


True

In [1]:
x="""hi my name is libass code
lets code"""

In [2]:
print(x)

hi my name is libass code
lets code


In [21]:
L=[1,2,3,4]  

L[1]=5
print(L)

[1, 5, 3, 4]


In [19]:

x="hello world"
x[1]

'e'

In [8]:
#list and strings are iterable.



In [9]:
x=23
x[1]
 

TypeError: 'int' object is not subscriptable

In [10]:
x="hello world"
x[-1]

'd'

In [17]:
c="bla bla bla bla bla i am laiba bla bla"
print (c[6])
print (c[7]) 

print (c[8])
print (c[9])
print (c[10])
print (c[20:31])
c[0]=1



a
 
b
l
a
i am laiba 


TypeError: 'str' object does not support item assignment

In [1]:
# STRING IS NOT MUTEABLE(WE CANOT CHNGE IT )
#LIST IS MUTEABLE(CAN BE CHNGE)


In [2]:
a="iam human"
print(a.upper())
print(a.lower())


IAM HUMAN
iam human


In [18]:
x="  zuhair baig  "
x.split()




['zuhair', 'baig']

In [20]:
x.lstrip()
x.rstrip()
print(x.lstrip())


zuhair baig  


In [21]:
x.strip()

'zuhair baig'

In [23]:
x.startswith("z")

False

In [25]:
x="dataesciezohairebaig"
x.split(sep="e")

['data', 'sci', 'zohair', 'baig']

In [1]:
l="i read in XO"
print(l.upper())
print(l.capitalize())
print(l.lower())

I READ IN XO
I read in xo
i read in xo


In [6]:
x="laiba khalid"
x.split()

['laiba', 'khalid']

In [13]:
x.lstrip()
x.rstrip()
print(x.lstrip())


laiba khalid


In [14]:
x.strip()

'laiba khalid'

In [17]:
x.startswith("l")


True

In [19]:
x="datallaibaable"
x.split(sep="l")

['data', '', 'aibaab', 'e']

In [1]:
x="u are human"
print(x.upper())
print(x.lower())
print(x.capitalize())

U ARE HUMAN
u are human
U are human


In [2]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [8]:
# data structures are list,dictioneries etc .
#muteable is that we can change.
#list can have duplicate items.
#and can have a list witin it.#we use square brackets in it.
# INDEX REPRESENTS THE POSITION IN THE LIST.
# E=[1,2,3]
#INDEX =[0,1,2]


In [11]:
L=[1,2,3]
L[0]
L[1]
L[2]
print(L[0])
print(L[1])
print(L[2])

1
2
3


In [19]:
b=[1,2,3]


In [17]:
s[0]
s[1]
s[2]

3

In [21]:
print(b[0])
print(b[1])
print(b[2])

1
2
3


In [23]:
L=[1,2,3,4,5]
L[2:5]

[3, 4, 5]

# Dictionaries
dictionaries consists of keys and values.
dict1={'keys".values,"key".value...}



In [3]:
dict1={"laiba":20,"shifa":19
     }

In [4]:
dict1["laiba"]

20

In [6]:
dict1["shifa"]


19

# Tuples 
is a scattered data. we cannot change its value.

In [7]:
help(tuple)

Help on class tuple in module builtins:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __

In [52]:
tup=(1,2,2,.3,4)

In [53]:
tup.count(2)

2

# Loops
1. while loop
2. for loop


In [17]:
a=0
while a<10:
    print(a)
    a=a+1

0
1
2
3
4
5
6
7
8
9


In [19]:
l=[0,1,2,3,4]
for i in l:
    print(i)
    
  

0
1
2
3
4


In [21]:
for i in range (10):
    print(i)
         

0
1
2
3
4
5
6
7
8
9


In [23]:
c=[1,2,3,4,5]
for l in c :
    print(l)
    

1
2
3
4
5


In [44]:
dict3={"my friend is":14,
"she scored":60
     }
for a in dict3:
    print(dict3[a])
    



14
60


In [1]:
dict4={"her lucky number is":2,
      "she wakes up at": 11
    }
for i in dict4:
    print(dict4[i])

2
11


In [16]:
str1 = "My name is"
str2 = "data is go"
i=0
while i <10:
    print(str1[i])
    print(str2[i])
    i=i+1

M
d
y
a
 
t
n
a
a
 
m
i
e
s
 
 
i
g
s
o


In [24]:
A1="my name is"
A2="data is go"
o=0
while o<7:

    print(A1[o])
    print(A2[o])
    o=o+1
    

m
d
y
a
 
t
n
a
a
 
m
i
e
s


# If Else 

If else is conditonal statement

In [1]:
x=19
if x>18:
    print("You can apply for id")
else:
    print("you are under 18")

You can apply for id


In [3]:
x=17
if x>18:
    print("you can apply for id")
else:
    print("you are under 18")

you are under 18


# If Alis marks are greatewr than 50 print Pass else print Fail

In [8]:
a=70
if a>50:
   
 print("he is pass")
else:    
    print("he is fail")

he is pass


# A House is being built how many lights are required for the house write a program that uses information to gues the number of lights in the house

In [21]:
Room=4
print("lights" , Room)

lights 4


# Use a for loop to print all the elements of the list


In [25]:
l = [1,2,3,4,5]
for i in l: 
    print(i) 



1
2
3
4
5


# Print the greatest element in the list using the if else statement and the for loop

In [31]:
l=[1,2,3,4]


1
1
1
2
2
3


In [3]:
l=[1,2,3,4]
min(l)
print(max(l))

4


# swap element using if else




In [9]:
om=[1,44,55,66]
om[3]=5
print(om)

[1, 44, 55, 5]


In [12]:
lf=[90,98,67]
lf[2]=9
print(lf)

[90, 98, 9]


# index

In [16]:
lf.index(90)

0

In [17]:
max(lf)
print(lf)

[90]


In [18]:
lf.index(90)

0

# sorting is use to arrange in acending to decending.
.

In [22]:
l = [4,3,2,1]
c=[]
for i in range(len(l)):
    a=min(l)
    x=l.index(a)
    l.pop(x)
    c.append(a)
    
    
    

In [5]:
c

[1, 2, 3, 4]

In [3]:
l=[1,2,3,4]
l.pop(3)
l

[1, 2, 3]

In [40]:
o=[1,2,3,4]
s=[]
for y in range(len(o)):
    d=max(o)
    h=o.index(d)
    o.pop(h)
    s.append(d)

In [41]:



s


[4, 3, 2, 1]

In [42]:
f=[1,2,4,5]
f.pop(1)
f

[1, 4, 5]

In [48]:
dic={"laiba":2,
     "shifa":3}




In [49]:
dic["laiba"]

2

In [55]:
dic8={"lisa":6,
   "lina":6,
   "elxa":8,
   "hermony":8,
  "harry":9,
    }
dic8.values()


dict_values([6, 6, 8, 8, 9])

# Functions

writing a function that calculates the sum of two numbers

In [8]:
def sum1(a,b):
    return(a+b)

now calling the function

In [9]:
sum1(5,5)

10

QUESTION Write a function to find the difference of two numbers

In [18]:
def difrence2(b,c):
    return(b-c)


In [19]:
difrence2(4,4)

0

Write a function for sorting in asscending order

In [20]:
 l = [4,3,2,1]
def sorting1(l):
    c=[]
    for i in range(len(l)):
        a=min(l)
        x=l.index(a)
        l.pop(x)
        c.append(a)
    return(c)
    

In [21]:
sorting1(l)

[1, 2, 3, 4]

In [30]:
z=[7,8,9,10]
def sorting2(z):
    c=[]
    for i in range(len(z)):
        a=max(z)
        x=z.index(a)
        z.pop(x)
        c.append(a)
    return(c)  


    

In [31]:
sorting2(z)

[10, 9, 8, 7]

In [10]:
f=[8,9,6,5]
def sorting3(f):
    d=[]
    for i in range(len(f)):
        a=min(f)
        x=f.index(a)
        f.pop(x)
        d.append(a)
    return(d)       

In [11]:
sorting3(f)

[5, 6, 8, 9]

In [47]:
l = [2,2,3,5]
max=l[3]
for i in l:
    if i >max:
        max = i

In [48]:
max


5

In [50]:
a=5,4

In [51]:
type(a)

tuple

# globel variable and local variable

In [70]:
l=[1,2,3]
def lp(l):
    global p
    p=0
    for p in l:
        print(p)
lp(l)

1
2
3


In [71]:
print(p)

3


# numpy

In [1]:
pip install numpy

In [3]:
import numpy as np

In [6]:
noofsales= np.array([[1,2,0],
        [1,1,2],
        [0,0,2]])

In [7]:
price = np.array([[10],
                 [50],
                 [20]])

In [10]:
noofsales.shape

(3, 3)

In [11]:
price.shape

(3, 1)

In [12]:
x=price.transpose()

In [13]:
x

array([[10, 50, 20]])

In [14]:
daysales=noofsales*x

In [15]:
daysales

array([[ 10, 100,   0],
       [ 10,  50,  40],
       [  0,   0,  40]])

In [26]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
cls